---
settings:
  name: StorageGRID
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: de-de,us-en,ja-jp,ko-kr,zh-cn,zh-tw,es-es,fr-fr,it-it
sidebar:
  entries:
  - title: StorageGRID Dokumentation
    url: "/index.html"
  - title: Versionshinweise
    entries:
    - title: Was ist neu
      url: "/whats-new.html"
    - title: Bekannte Probleme
      url: "/reference-known-issues.html"
  - title: Los geht's
    entries:
    - title: StorageGRID Systeme erkennen
      url: "/task-discover-storagegrid.html"
  - title: Managen Sie StorageGRID Systeme
    entries:
    - title: Sehen Sie Ihre StorageGRID Systeme an
      url: "/task-view-storagegrid.html"
    - title: Verwalten von Zertifikaten
      url: "/task-manage-certificates.html"
    - title: Verwalten Sie StorageGRID über die erweiterte Ansicht
      url: task-administer-storagegrid.html
    - title: Nutzen Sie NetApp Datenservices mit StorageGRID
      url: "/task-enable-data-services.html"
    - title: Entfernen Sie eine Arbeitsumgebung
      url: "/task-remove-storagegrid.html"
  - title: Wissen und Support
    entries:
    - title: Für den Support anmelden
      url: "/task-support-registration.html"
    - title: Holen Sie sich Hilfe
      url: "/task-get-help.html"
  - title: Rechtliche Hinweise
    url: "/legal-notices.html"
product-family:
  name: BlueXP
  repo: bluexp-family
