---
sidebar: sidebar 
permalink: task-enable-data-services.html 
keywords: storagegrid, cloud sync, cloud backup, backup, back up data 
summary: Nachdem Sie ein StorageGRID System in BlueXP entdeckt haben, können Sie die Datenservices von NetApp mit StorageGRID für Backups und die Datensynchronisierung nutzen. 
---
= Nutzen Sie NetApp Datenservices mit StorageGRID
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Nachdem Sie ein StorageGRID System in BlueXP entdeckt haben, können Sie die Datenservices von NetApp für Backups und die Datensynchronisierung nutzen.

* Mit BlueXP Backup und Recovery erstellen Sie Backups von Daten aus Ihren lokalen ONTAP Systemen auf Objekt-Storage in Ihren NetApp StorageGRID Systemen.
+
Um zu beginnen, öffnen Sie den BlueXP Arbeitsbereich und ziehen eine lokale ONTAP Arbeitsumgebung in Ihrer StorageGRID Arbeitsumgebung per Drag & Drop.

+
https://docs.netapp.com/us-en/bluexp-backup-recovery/task-backup-onprem-private-cloud.html["Weitere Informationen zum Backup von On-Premises-ONTAP-Daten in StorageGRID"^]

* BlueXP Kopier- und Synchronisierungsfunktion ermöglicht die Synchronisierung von Daten mit oder von einem StorageGRID System.
+
Um zu beginnen, gehen Sie zum BlueXP Arbeitsbereich und ziehen Sie die Quell-Arbeitsumgebung in der Zielumgebung. Als StorageGRID kann die Quelle oder das Ziel verwendet werden.

+
https://docs.netapp.com/us-en/bluexp-copy-sync/index.html["Weitere Informationen zum Kopieren und Synchronisieren von BlueXP"^]


