---
sidebar: sidebar 
permalink: whats-new.html 
keywords: 'what"s new, features, new, release notes, bugs, limitations, known issues, enhancements, fixes, storagegrid' 
summary: Erfahren Sie, welche Neuerungen beim Management von StorageGRID Systemen in BlueXP sind. 
---
= Was ist neu bei StorageGRID Management
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Erfahren Sie, welche Neuerungen beim Management von StorageGRID Systemen in BlueXP sind.



== 12 Mai 2025



=== Benötigte BlueXP -Zugriffsrollen

Sie benötigen jetzt eine der folgenden Zugriffsrollen, um StorageGRID in BlueXP anzuzeigen, zu entdecken oder zu verwalten: *Organisationsadministrator*, *Ordner- oder Projektadministrator*, *Speicheradministrator* oder *Speicherintegritätsspezialist*. link:https://docs.netapp.com/us-en/bluexp/reference-iam-predefined-roles.html["Erfahren Sie mehr über BlueXP-Zugriffsrollen."^]



== 7 August 2024



=== Neue erweiterte Ansicht

Ab StorageGRID 11.8 können Sie das StorageGRID System über die vertraute Grid-Manager-Oberfläche von BlueXP  aus verwalten.

https://docs.netapp.com/us-en/bluexp-storagegrid/task-administer-storagegrid.html["Erfahren Sie, wie Sie StorageGRID mithilfe der erweiterten Ansicht verwalten"].



=== Fähigkeit zur Überprüfung und Genehmigung des Zertifikats der StorageGRID Managementoberfläche

Sie können jetzt ein Zertifikat für die StorageGRID Managementoberfläche prüfen und genehmigen, wenn Sie das StorageGRID System von BlueXP  aus ermitteln. Sie können auch das neueste Zertifikat für die StorageGRID Managementoberfläche in einem erkannten Raster prüfen und genehmigen.

https://docs.netapp.com/us-en/bluexp-storagegrid/task-discover-storagegrid.html["Erfahren Sie, wie Sie das Serverzertifikat während der Systemerkennung überprüfen und genehmigen."]



== 18. September 2022



=== Unterstützung von StorageGRID

Sie können Ihre StorageGRID-Systeme jetzt direkt bei BlueXP entdecken. Die Entdeckung von StorageGRID verschafft Ihnen eine vollständige Übersicht über die Daten in Ihrer gesamten Hybrid-Multi-Cloud.
